import type { EvaluationForm } from './types'

export const quiz1b: EvaluationForm = {
  slug: 'quiz-1b',
  title: 'Quizz Informatique (Niveau 1B)',
  shortTitle: 'Quiz 1B',
  description:
    'Dossiers, Internet, messagerie et Word : un quiz pour consolider les acquis du niveau 1.',
  kind: 'quiz',
  badgeLabel: 'Quiz',
  heroImage: '/assets/TS/courses/numerique/messagerie-electronique.jpg',
  heroImageAlt: 'Messagerie et bureautique',
  questions: [
    {
      id: 'q1',
      type: 'radio',
      prompt: 'Un dossier sert à ?',
      options: [
        'Lire des fichiers textes, sons, images, et vidéos',
        'Organiser ses fichiers',
        'Faire des copier / coller',
      ],
      correct: ['Organiser ses fichiers'],
    },
    {
      id: 'q2',
      type: 'checkboxes',
      prompt: 'Comment crée-t-on un dossier ? (choix multiple)',
      options: [
        'Ctrl + Shift + N',
        'Clic droit → Créer un dossier',
        'Clic droit → Nouveau → Dossier',
      ],
      correct: ['Ctrl + Shift + N', 'Clic droit → Nouveau → Dossier'],
    },
    {
      id: 'q3',
      type: 'radio',
      prompt: 'Quand j’envoie mes fichiers à la corbeille ils sont supprimés de l’ordinateur ?',
      options: ['Oui', 'Non'],
      correct: ['Non'],
    },
    {
      id: 'q4',
      type: 'radio',
      prompt: 'Pour accéder à Internet je vais sur ?',
      options: [
        'N’importe quel moteur de recherche',
        'Un navigateur',
        'Le lecteur multimédia',
        'Le gestionnaire de tâches',
      ],
      correct: ['Un navigateur'],
    },
    {
      id: 'q5',
      type: 'radio',
      prompt: 'Un lien sert à ?',
      options: [
        'Accéder directement à une autre page web ou un document',
        'Augmenter la vitesse de l’ordinateur',
        'Modifier un fichier sur l’ordinateur',
        'Créer un nouveau compte utilisateur',
      ],
      correct: ['Accéder directement à une autre page web ou un document'],
    },
    {
      id: 'q6',
      type: 'radio',
      prompt: 'Est-ce qu’il y a un @ dans une adresse de site Internet ?',
      options: ['Oui', 'Non'],
      correct: ['Non'],
    },
    {
      id: 'q7',
      type: 'radio',
      prompt: 'À quoi servent les onglets du navigateur ?',
      options: [
        'À ranger ses sites web favoris',
        'Ouvrir plusieurs pages web en même temps',
        'À enregistrer un contenu',
      ],
      correct: ['Ouvrir plusieurs pages web en même temps'],
    },
    {
      id: 'q8',
      type: 'radio',
      prompt: 'Pour envoyer le même e-mail à plusieurs personnes je dois ?',
      options: [
        'Créer plusieurs adresses e-mail',
        'Entrer plusieurs adresses dans le champ des destinataires',
        'Recommencer plusieurs fois mon envoi d’e-mail',
      ],
      correct: ['Entrer plusieurs adresses dans le champ des destinataires'],
    },
    {
      id: 'q9',
      type: 'radio',
      prompt: 'Qu’est-ce que le spam dans une boîte e-mail ?',
      imageSrc: '/assets/evaluations/quiz-1b/q9.png',
      imageAlt: 'Exemple de spam',
      options: [
        'Des messages importants à lire immédiatement',
        'Des e-mails non sollicités ou potentiellement dangereux, souvent publicitaires',
        'Des e-mails envoyés par des amis',
        'Des messages que vous avez envoyés',
      ],
      correct: ['Des e-mails non sollicités ou potentiellement dangereux, souvent publicitaires'],
    },
    {
      id: 'q10',
      type: 'radio',
      prompt: 'Je peux avoir plusieurs adresses mail ?',
      options: ['Oui', 'Non'],
      correct: ['Oui'],
    },
    {
      id: 'q11',
      type: 'radio',
      prompt: 'À quoi servent les dossiers de messageries ?',
      options: [
        'À classer ses messages électroniques',
        'À rien',
        'À stocker les pièces jointes',
      ],
      correct: ['À classer ses messages électroniques'],
    },
    {
      id: 'q12',
      type: 'radio',
      prompt: 'Je peux insérer des graphiques et des images dans un document Word ?',
      imageSrc: '/assets/evaluations/quiz-1b/q12.png',
      imageAlt: 'Insertion dans Word',
      options: ['Vrai', 'Faux'],
      correct: ['Vrai'],
    },
    {
      id: 'q13',
      type: 'radio',
      prompt: 'Dans Microsoft Word, le raccourci CTRL + A est utilisé pour ?',
      options: [
        'Ouvrir la boîte de dialogue « Imprimer »',
        'Mettre à jour la page Web actuelle',
        'Fermer les fenêtres en cours',
        'Sélectionner tout le document',
      ],
      correct: ['Sélectionner tout le document'],
    },
    {
      id: 'q14',
      type: 'checkboxes',
      prompt: 'Quelles sont le(s) extension(s) des fichiers Word : (choix multiple)',
      options: ['.pdf', '.doc', '.xls', '.docx'],
      correct: ['.doc', '.docx'],
    },
    {
      id: 'q15',
      type: 'radio',
      prompt: 'Comment supprime-t-on une colonne dans un tableau créé dans Word ?',
      options: [
        'Il faut sélectionner la colonne et la supprimer avec le raccourci clavier CTRL+V',
        'C’est uniquement possible à partir du menu « Outils/Tableau »',
        'En se plaçant dans une cellule de la colonne et en appuyant sur la touche « SUPPR »',
      ],
      correct: ['C’est uniquement possible à partir du menu « Outils/Tableau »'],
    },
    {
      id: 'q16',
      type: 'checkboxes',
      prompt: 'Quel outil de Microsoft Word permet de vérifier l’orthographe et la grammaire ? (choix multiple)',
      options: [
        'L’outil « Grammaire et orthographe »',
        'Le « Correcteur automatique »',
        'Le « Tableau de bord »',
        'Le « Navigateur Internet »',
      ],
      correct: ['L’outil « Grammaire et orthographe »', 'Le « Correcteur automatique »'],
    },
    {
      id: 'q17',
      type: 'checkboxes',
      prompt: 'Comment pouvez-vous insérer un saut de page dans un document Word ? (choix multiple)',
      options: [
        'En appuyant sur « Entrée » plusieurs fois jusqu’à atteindre la nouvelle page',
        'En allant dans l’onglet « Insertion » et en sélectionnant « Saut de page »',
        'En utilisant la combinaison de touches Ctrl + Entrée',
        'En copiant le contenu de la page précédente dans la nouvelle page',
      ],
      correct: [
        'En allant dans l’onglet « Insertion » et en sélectionnant « Saut de page »',
        'En utilisant la combinaison de touches Ctrl + Entrée',
      ],
    },
    {
      id: 'q18',
      type: 'radio',
      prompt: 'Comment pouvez-vous créer des colonnes dans un document Word ?',
      options: [
        'En sélectionnant le texte, puis en allant dans l’onglet « Mise en page » et en choisissant « Colonnes »',
        'En insérant un tableau et en masquant les bordures',
        'En copiant et en collant le texte plusieurs fois sur la même ligne',
        'En modifiant les marges du document',
      ],
      correct: [
        'En sélectionnant le texte, puis en allant dans l’onglet « Mise en page » et en choisissant « Colonnes »',
      ],
    },
    {
      id: 'q19',
      type: 'radio',
      prompt: 'Que permet de faire l’option « Afficher tout » dans Microsoft Word ?',
      imageSrc: '/assets/evaluations/quiz-1b/q19.png',
      imageAlt: 'Option Afficher tout dans Word',
      options: [
        'Voir tous les caractères non imprimables, comme les espaces et les sauts de paragraphe',
        'Afficher tous les documents ouverts dans une seule fenêtre',
        'Imprimer tous les documents ouverts en une seule fois',
        'Révéler tous les fichiers cachés',
      ],
      correct: ['Voir tous les caractères non imprimables, comme les espaces et les sauts de paragraphe'],
    },
    {
      id: 'q20',
      type: 'radio',
      prompt: 'Quelle est la fonction principale de la barre des tâches dans Windows ?',
      options: [
        'Stocker des fichiers et des documents',
        'Afficher les applications ouvertes et accéder rapidement à des programmes',
        'Modifier les paramètres de l’ordinateur',
        'Exécuter des analyses antivirus',
      ],
      correct: ['Afficher les applications ouvertes et accéder rapidement à des programmes'],
    },
    {
      id: 'difficulty',
      type: 'radio',
      prompt: 'Comment avez-vous trouvé ce quizz ?',
      options: ['Trop facile', 'Facile', 'Intermédiaire', 'Difficile', 'Trop difficile'],
    },
  ],
}
