import type { EvaluationForm } from './types'

export const quiz1a: EvaluationForm = {
  slug: 'quiz-1a',
  title: 'Quizz Informatique (Niveau 1A)',
  shortTitle: 'Quiz 1A',
  description:
    'Vérifiez vos bases : matériel, clavier, Windows, Word et messagerie.',
  kind: 'quiz',
  badgeLabel: 'Quiz',
  heroImage: '/assets/services/perfectionnement/office.jpg',
  heroImageAlt: 'Initiation à l’informatique',
  questions: [
    {
      id: 'q1',
      type: 'radio',
      prompt: 'Quel est l’objet montré sur l’image ci-dessous ?',
      imageSrc: '/assets/evaluations/quiz-1a/q1.png',
      imageAlt: 'Objet informatique',
      options: ['Un clavier', 'Une souris', 'Un écran', 'Un scanner'],
      correct: ['Un clavier'],
    },
    {
      id: 'q2',
      type: 'radio',
      prompt: 'Quel est l’objet montré sur l’image ci-dessous ?',
      imageSrc: '/assets/evaluations/quiz-1a/q2.png',
      imageAlt: 'Objet informatique',
      options: ['Un clavier', 'Une souris', 'Une imprimante', 'Un disque dur'],
      correct: ['Une souris'],
    },
    {
      id: 'q3',
      type: 'radio',
      prompt: 'Comment s’appelle cette action ?',
      imageSrc: '/assets/evaluations/quiz-1a/q3.png',
      imageAlt: 'Action de la souris',
      options: ['Clic gauche', 'Clic droit', 'Clic molette'],
      correct: ['Clic droit'],
    },
    {
      id: 'q4',
      type: 'radio',
      prompt: 'Si on tape en même temps sur ces touches, on obtient ?',
      imageSrc: '/assets/evaluations/quiz-1a/q4.png',
      imageAlt: 'Combinaison de touches',
      options: ['A', 'a', 'à', '@'],
      correct: ['A'],
    },
    {
      id: 'q5',
      type: 'radio',
      prompt: 'À quoi correspond l’icône ?',
      imageSrc: '/assets/evaluations/quiz-1a/q5.png',
      imageAlt: 'Icône Windows',
      options: ['Démarrer', 'Explorateur de fichier', 'Notificateur', 'Navigateur'],
      correct: ['Démarrer'],
    },
    {
      id: 'q6',
      type: 'radio',
      prompt: 'Que fait cette option dans Word ?',
      imageSrc: '/assets/evaluations/quiz-1a/q6.png',
      imageAlt: 'Option Word',
      options: ['Mettre le texte en gras', 'Mettre le texte en italique', 'Mettre le texte souligné'],
      correct: ['Mettre le texte en gras'],
    },
    {
      id: 'q7',
      type: 'radio',
      prompt: 'Que se passe-t-il si on appuie sur la touche :',
      imageSrc: '/assets/evaluations/quiz-1a/q7.png',
      imageAlt: 'Touche du clavier',
      options: [
        'Saut à la ligne ou commande validé',
        'Fermer le programme',
        'Supprime du texte',
        'Ajoute un espace',
      ],
      correct: ['Saut à la ligne ou commande validé'],
    },
    {
      id: 'q8',
      type: 'checkboxes',
      prompt: 'Lesquels sont des navigateurs ? (choix multiple)',
      options: ['Chrome', 'Edge', 'Firefox', 'Yahoo'],
      correct: ['Chrome', 'Edge', 'Firefox'],
    },
    {
      id: 'q9',
      type: 'radio',
      prompt: 'Comment s’appelle cette partie sur Word ?',
      imageSrc: '/assets/evaluations/quiz-1a/q9.png',
      imageAlt: 'Interface Word',
      options: ['Le bandeau', 'Le ruban', 'L’écharpe', 'L’onglet'],
      correct: ['Le ruban'],
    },
    {
      id: 'q10',
      type: 'radio',
      prompt: 'Si on tape en même temps sur ces touches, on obtient ?',
      imageSrc: '/assets/evaluations/quiz-1a/q10.png',
      imageAlt: 'Combinaison de touches',
      options: ['E', 'e', '€', 'é'],
      correct: ['€'],
    },
    {
      id: 'q11',
      type: 'radio',
      prompt: 'Quel est l’objet montré sur l’image ci-dessous ?',
      imageSrc: '/assets/evaluations/quiz-1a/q11.png',
      imageAlt: 'Objet informatique',
      options: ['Un écran d’ordinateur', 'Un clavier', 'Une souris', 'Un haut-parleur'],
      correct: ['Un écran d’ordinateur'],
    },
    {
      id: 'q12',
      type: 'radio',
      prompt: 'On clique sur quel bouton pour fermer la fenêtre ?',
      imageSrc: '/assets/evaluations/quiz-1a/q12.png',
      imageAlt: 'Boutons d’une fenêtre',
      options: ['1', '2', '3'],
      correct: ['3'],
    },
    {
      id: 'q13',
      type: 'radio',
      prompt: 'Comment on lance ce programme depuis le bureau Windows ?',
      imageSrc: '/assets/evaluations/quiz-1a/q13.png',
      imageAlt: 'Icône de programme sur le bureau',
      options: [
        'Un clic gauche',
        'Un clic droit',
        'Double clic gauche',
        'Double clic droit',
        'Un clic molette',
        'Double clic molette',
      ],
      correct: ['Double clic gauche'],
    },
    {
      id: 'q14',
      type: 'radio',
      prompt: 'Si on tape en même temps sur ces touches, on obtient ?',
      imageSrc: '/assets/evaluations/quiz-1a/q14.png',
      imageAlt: 'Combinaison de touches',
      options: ['2', 'é', '@'],
      correct: ['@'],
    },
    {
      id: 'q15',
      type: 'radio',
      prompt: 'Quel bouton utiliser pour réduire la fenêtre ?',
      imageSrc: '/assets/evaluations/quiz-1a/q15.png',
      imageAlt: 'Boutons d’une fenêtre',
      options: ['1', '2', '3'],
      correct: ['1'],
    },
    {
      id: 'q16',
      type: 'radio',
      prompt: 'Que se passe-t-il si vous cliquez sur l’icône suivante dans Gmail ?',
      imageSrc: '/assets/evaluations/quiz-1a/q16.png',
      imageAlt: 'Icône Gmail',
      options: [
        'Créer un nouveau message pour envoyer un e-mail',
        'Lire vos e-mails',
        'Supprimer tous les e-mails',
        'Archiver un e-mail',
      ],
      correct: ['Créer un nouveau message pour envoyer un e-mail'],
    },
    {
      id: 'q17',
      type: 'radio',
      prompt: 'Que permet de faire cette icône dans Word ?',
      imageSrc: '/assets/evaluations/quiz-1a/q17.png',
      imageAlt: 'Icône Word',
      options: [
        'Supprimer un document',
        'Sauvegarder le document',
        'Ouvrir un nouveau document',
        'Imprimer un document',
      ],
      correct: ['Sauvegarder le document'],
    },
    {
      id: 'q18',
      type: 'radio',
      prompt: 'Que se passe-t-il quand on appuie sur ce bouton ?',
      imageSrc: '/assets/evaluations/quiz-1a/q18.png',
      imageAlt: 'Bouton d’ordinateur',
      options: [
        'Il allume et éteint l’ordinateur',
        'Il lance un programme',
        'Il ouvre le menu Démarrer',
        'Il ajuste la luminosité de l’écran',
      ],
      correct: ['Il allume et éteint l’ordinateur'],
    },
    {
      id: 'q19',
      type: 'radio',
      prompt: 'Que se passe-t-il si on appuie sur la touche :',
      imageSrc: '/assets/evaluations/quiz-1a/q19.png',
      imageAlt: 'Touche du clavier',
      options: [
        'Insère un espace entre les mots.',
        'Supprime un caractère',
        'Ouvre le menu Démarrer',
        'Saut à la ligne',
      ],
      correct: ['Insère un espace entre les mots.'],
    },
    {
      id: 'q20',
      type: 'radio',
      prompt: 'Comment pouvez-vous éteindre correctement un ordinateur sous Windows ?',
      options: [
        'Débrancher l’ordinateur',
        'Appuyer sur le bouton « Démarrer », puis cliquer sur « Arrêter »',
        'Appuyer sur la touche « Entrée »',
        'Fermer l’écran de l’ordinateur portable',
      ],
      correct: ['Appuyer sur le bouton « Démarrer », puis cliquer sur « Arrêter »'],
    },
    {
      id: 'q21',
      type: 'radio',
      prompt: 'À quoi sert cette touche ?',
      imageSrc: '/assets/evaluations/quiz-1a/q21.png',
      imageAlt: 'Touche du clavier',
      options: [
        'Ouvre le menu Démarrer',
        'Fermer toutes les fenêtres ouvertes',
        'Éteint immédiatement l’ordinateur',
        'Change de fenêtre ouverte',
      ],
      correct: ['Ouvre le menu Démarrer'],
    },
    {
      id: 'q22',
      type: 'radio',
      prompt: 'À quoi sert la boîte de réception ?',
      imageSrc: '/assets/evaluations/quiz-1a/q22.png',
      imageAlt: 'Boîte de réception',
      options: [
        'Stocker tous les fichiers et documents sur l’ordinateur',
        'Recevoir et consulter tous les e-mails entrants',
        'Envoyer des e-mails uniquement',
        'Configurer les paramètres de l’ordinateur',
      ],
      correct: ['Recevoir et consulter tous les e-mails entrants'],
    },
    {
      id: 'q23',
      type: 'radio',
      prompt: 'Qu’est-ce que représente cette icône dans Gmail ?',
      imageSrc: '/assets/evaluations/quiz-1a/q23.png',
      imageAlt: 'Icône Gmail',
      options: ['Supprimer un message', 'Enregistrer un document', 'Pièce jointe', 'Envoyer un e-mail'],
      correct: ['Pièce jointe'],
    },
    {
      id: 'q24',
      type: 'radio',
      prompt: 'À quoi sert cette touche dans Word ?',
      imageSrc: '/assets/evaluations/quiz-1a/q24.png',
      imageAlt: 'Touche du clavier',
      options: [
        'Supprime un caractère',
        'Déplace le curseur vers la gauche',
        'Ouvre le menu fichier',
        'Enregistre le document',
      ],
      correct: ['Supprime un caractère'],
    },
    {
      id: 'q25',
      type: 'radio',
      prompt: 'Quel appareil utilisez-vous pour déplacer le curseur sur l’écran ?',
      imageSrc: '/assets/evaluations/quiz-1a/q25.png',
      imageAlt: 'Appareil informatique',
      options: ['Le clavier', 'La souris', 'L’imprimante', 'Le scanner'],
      correct: ['La souris'],
    },
    {
      id: 'difficulty',
      type: 'radio',
      prompt: 'Comment avez-vous trouvé ce quizz ?',
      options: ['Trop facile', 'Facile', 'Intermédiaire', 'Difficile', 'Trop difficile'],
    },
  ],
}
